# Generated by Django 4.2.30 on 2026-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_add_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
