# Generated by Django 5.0.4 on 2026-04-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rc7", "0003_rc7plan_deliverable_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="rc7plan",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
