# Generated by Django 5.1.1 on 2026-01-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EXTERNAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_lead_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_lead',
            field=models.ForeignKey(limit_choices_to={'role': 'SGM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sgm_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['EMPLOYEE', 'EXTERNAL']}, related_name='project_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
