# Generated by Django 5.1.1 on 2026-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0004_project_external_lead_project_external_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='projects', to='employees.employee'),
        ),
    ]
