# Generated by Django 5.0.4 on 2026-06-30 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_assigned_coo_alter_project_assigned_sgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EXTERNAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
