# Generated by Django 5.0.4 on 2026-07-02 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_remove_coo_widen_sgm_hqepl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_lead',
            field=models.ForeignKey(limit_choices_to={'role': 'EXTERNAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_team',
            field=models.ManyToManyField(limit_choices_to={'role': 'EXTERNAL'}, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
