# Generated by Django 4.2.30 on 2026-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddfms", "0002_ddfmsdeliverable_is_submitted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ddfmsdeliverable",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
