# Generated by Django 5.1.1 on 2026-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_is_active_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HQEPL', 'HQEPL'), ('SGM', 'SGM'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('EXTERNAL', 'External')], default='employee', max_length=20),
        ),
    ]
