# Generated by Django 5.1.1 on 2026-01-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HQEPL', 'HQEPL'), ('SGM', 'SGM'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('EXTERNAL', 'External')], default='EMPLOYEE', max_length=20),
        ),
    ]
