# Generated by Django 5.0.4 on 2026-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_experience_customuser_expertise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="shortform",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
