# Generated by Django 5.0.4 on 2026-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HQEPL', 'CEO'), ('MLS', 'MLS'), ('SGM', 'SGM'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client'), ('EXTERNAL', 'External'), ('SENIOR', 'Senior'), ('COO', 'COO')], default='EMPLOYEE', max_length=20),
        ),
    ]
