# Generated by Django 5.1.1 on 2026-01-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_externalteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteam',
            name='role',
            field=models.CharField(default='client_external', max_length=50),
        ),
        migrations.AlterField(
            model_name='externalteam',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_members', to='clients.client'),
        ),
    ]
