# Generated by Django 5.0.4 on 2026-02-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0009_externalteam_credential_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("hold", "Hold"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
