# Generated by Django 5.0.4 on 2026-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_alter_client_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_hierarchy",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
