# Generated by Django 5.0.4 on 2026-02-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddtme', '0002_ddtmeadditionaltask_mandayentry_ddtmesubmission'),
        ('projects', '0008_actionplan_actiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddtmeadditionaltask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ddtme_additional_tasks', to='projects.project'),
        ),
    ]
