# Generated by Django 5.0.4 on 2026-02-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_externalteam_credential_access_and_more'),
        ('ddtme', '0003_ddtmeadditionaltask_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDTMEMonthlyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('objective', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_objectives', to='clients.client')),
            ],
        ),
    ]
