# Generated by Django 5.0.4 on 2026-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddtme", "0004_ddtmemonthlyobjective"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandayentry",
            name="off_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="mandayentry",
            name="plan_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
