# Generated by Django 5.0.4 on 2026-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddtme", "0007_bigtask_ddtme_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bigtask",
            name="ddtme_title",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="bigtask",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="ddtmeadditionaltask",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
