# Generated by Django 5.0.4 on 2026-02-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mctc", "0002_mctcentry_linked_task"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mctcentry",
            new_name="mctc_mctcen_user_id_42671c_idx",
            old_name="mctc_mctcen_user_id_7f4f53_idx",
        ),
    ]
