# Generated by Django 5.0.4 on 2026-04-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mctc", "0004_mctcentry_source_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mctcentry",
            name="source_module",
        ),
    ]
