# Generated by Django 4.2.30 on 2026-05-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_add_task_priority"),
        ("mctc", "0005_remove_mctcentry_source_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mctcentry",
            name="linked_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_mctc_entries",
                to="tasks.task",
            ),
        ),
    ]
