# Generated by Django 4.2.30 on 2026-06-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mctc", "0006_alter_mctcentry_linked_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="mctcentry",
            name="half_type",
            field=models.CharField(
                choices=[("first_half", "First Half"), ("second_half", "Second Half")],
                default="first_half",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="mctcentry",
            name="last_revision_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mctcentry",
            name="original_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mctcentry",
            name="revision_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="MCTCEntryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_date", models.DateField()),
                ("new_date", models.DateField()),
                ("old_half", models.CharField(max_length=15)),
                ("new_half", models.CharField(max_length=15)),
                ("moved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_history",
                        to="mctc.mctcentry",
                    ),
                ),
                (
                    "moved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["moved_at"],
            },
        ),
    ]
